FastKart/Areas/AdminPanel/Controllers/CategoryController.cs
using FastKart.DAL;
using FastKart.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace FastKart.Areas.AdminPanel.Controllers
{
    public class CategoryController : AdminController
    {
        private readonly AppDbContext _contex;
        public CategoryController(AppDbContext contex)
        {
            _contex = contex;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await _contex.Categories.ToListAsync();
            return View(categories);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var category = await _contex.Categories.FirstOrDefaultAsync(x => x.Id == id);
            if (category == null) return NotFound();
            return View(category);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var isExist = await _contex.Categories.AnyAsync(x => x.Name.ToLower().Equals(category.Name.ToLower()));
            if (isExist)
            {
                ModelState.AddModelError("Name", "Bu adda kateqoriya movcuddur");
                return View();
            }
            await _contex.Categories.AddAsync(category);
            await _contex.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var category = await _contex.Categories.FirstOrDefaultAsync(x => x.Id == id);
            if (category == null) return NotFound();

            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _contex.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            _contex.Categories.Remove(category);
            await _contex.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }



    }
}

FastKart/Areas/AdminPanel/Controllers/SliderController.cs
using FastKart.Constans;
using FastKart.DAL;
using FastKart.DAL.Entities;
using FastKart.Extencions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FastKart.Areas.AdminPanel.Controllers;

[Area("AdminPanel")]
public class SliderController : Controller
{
    private readonly AppDbContext _context;
    private readonly IWebHostEnvironment _webHostEnvironment;
    public SliderController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
    {
        _context = context;
        _webHostEnvironment = webHostEnvironment;
    }
    public async Task<IActionResult> Index()
    {

        var sliders = await _context.Sliders.ToListAsync();
        return View(sliders);
    }
    public IActionResult Create()
    {

        return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Slider slider)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
    

        if (!slider.ImageFile.IsImage())
        {
            ModelState.AddModelError("ImageFile", "Please add image format");

            return View();
        }

        if (!slider.ImageFile.CheckSize(2))
        {
            ModelState.AddModelError("ImageFile", "Images length should be less than 1gb");

            return View();
        }

        var imageName = await slider.ImageFile.GenerateFileAsync(FileConstans.SliderImagePath );
        slider.ImageUrl = imageName;
       
        await _context.Sliders.AddAsync(slider);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }

}

FastKart/Areas/AdminPanel/Views/Slider/Create.cshtml
@model Slider
<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create Category</h4>
                <form class="forms-sample" method="post" enctype="multipart/form-data" >
                   
                    <div class="form-group">
                        <label asp-for="OfferName"> OfferName</label>
                        <input asp-for="OfferName" class="form-control" placeholder="OfferName">
                        <span asp-validation-for="OfferName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Title">Title</label>
                        <input asp-for="Title" class="form-control" placeholder="Title">
                        <span asp-validation-for="Title"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Description">Description</label>
                        <input asp-for="Description" class="form-control" placeholder="Description">
                        <span asp-validation-for="Description "></span>
                    </div>
                       

                    <div class="form-group">
                        <label asp-for="ImageFile">Image</label>
                        <input asp-for="ImageFile" class="form-control" placeholder="Enter image URL">
                        <span asp-validation-for="ImageFile"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-light" asp-controller="index">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

FastKart/Areas/AdminPanel/Views/Slider/Index.cshtml
@model List<Slider>
<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Sliders</h4>
            <a  asp-controller="Slider" asp-action="Create" class="btn btn-success">Create Slider</a>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>OfferName</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Image</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.OfferName</td>
                                <td>@item.Title</td>
                                <td>
                                    <a class="btn btn-primary" asp-controller="category" asp-action="details" asp-route-id="@item.Id">Details</a>
                                    <a class="btn btn-warning">Update</a>
                                    <form asp-controller="Category" asp-action="Delete" method="post" style="display:inline;">
                                        <input type="hidden" name="id" value="@item.Id" />
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                <td>
                                    <a href="product-left-thumbnail.html">
                                        <img src="~/assets/images/fashion/banner/@item.ImageUrl" class="img-fluid blur-up lazyload" alt="">
                                    </a>
                            </tr>

                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>